<?php

namespace Blunx\AI\Support;

use Blunx\AI\Support\BlunxDatabase;
use Blunx\AI\Support\SqlGuard;

/**
 * Executes the reference queries generated by the cloud server locally.
 *
 * Each reference query is a read-only metric (e.g. overall average) used to
 * give the insight agent a baseline to compare the widget data against.
 */
class ReferenceQueryExecutor
{
    /**
     * Run reference queries and return metric → {sql, description, result}.
     */
    public static function execute(array $referenceQueries): array
    {
        $results = [];

        foreach ($referenceQueries as $metric => $item) {
            // Support legacy (string SQL) et nouveau format (array avec sql/description)
            if (is_string($item)) {
                $sql         = trim($item);
                $description = $metric;
            } else {
                $sql         = trim($item['sql'] ?? '');
                $description = $item['description'] ?? $metric;
            }

            // Safety net: only run read-only SELECT/WITH queries.
            if (!SqlGuard::isReadOnly($sql)) continue;

            $entry = [
                'sql'         => $sql,
                'description' => $description,
                'result'      => null,
            ];

            try {
                $rows = BlunxDatabase::select($sql);
                if (!empty($rows)) {
                    $row   = (array) $rows[0];
                    $value = reset($row);
                    $entry['result'] = is_numeric($value) ? (float) $value : $value;
                }
            } catch (\Throwable) {
                // result reste null
            }

            $results[$metric] = $entry;
        }

        return $results;
    }

}