<?php

return [
    'delete_confirm' => 'Delete this insight?',
    'download_report' => 'Download full report',
    'mark_read' => 'Read',
    'report_title' => 'Blunx AI Report',
    'generated_at' => 'Report generated on',
    'footer' => 'Report automatically generated by Blunx AI. Internal use only.',
    'severity.critical' => 'Critical',
    'severity.warning' => 'Warning',
    'severity.info' => 'Informational',
    'type.anomaly' => 'Anomaly detected',
    'type.trend' => 'Notable trend',
    'type.record' => 'Record detected',
    'type.info' => 'Periodic report',
    'no_data_message' => 'Widget ":title" returns no data — possible data feed interruption.',
    'no_data_indicator' => 'Data volume',
    'no_data_value' => '0 rows',
    'no_data_previous' => ':count rows',
    'first_run' => 'First run — no previous data.',
    'current_data_label' => 'Current data',
    'previous_data_label' => 'Previous data',
    'trend.down' => 'Downward trend ↓',
    'trend.up' => 'Upward trend ↑',
    'trend.mixed' => 'Mixed signal ↕',
    'trend.stable' => 'Stable →',
    'correlation.header' => 'METRIC CORRELATIONS:',
    'correlation.contraction' => 'Global contraction — both metrics dropping together',
    'correlation.growth' => 'Joint growth — both metrics rising together',
    'correlation.mix_shift_a' => 'Mix-shift — :metricA eroding while :metricB compensates',
    'correlation.mix_shift_b' => 'Mix-shift — :metricB eroding while :metricA compensates',
    'correlation.stable' => 'Stable',
    'correlation.ratio' => '    → Metric ratio: :value',
    'trend.header' => 'TRENDS OVER MULTIPLE RUNS:',
    'trend.row' => '  :arrow :col : :slope%/run (consistency :consistency%, total: :total%, over :runs runs)',
    'prev_context.none' => 'PREVIOUS REPORT: None (first report for this widget).',
    'prev_data.none' => 'No previous data (first report).',
    'prev_json.none' => 'None',
    'prev_context.full' => 'PREVIOUS REPORT:
- Indicator      : :indicator
- Observed value : :value
- Variation at the time: :variation
- Conclusion     : ":message"
- Generated on   : :date',
    'scores_block' => 'EVOLUTION SIGNALS (algorithmically calculated — include in report):
- Activity       : :impact/100
- Pressure       : :risk/100
- Concentration  : :dep/100
- Instability    : :volatility/100
- Divergence     : :corr/100
- Trend          : :trend/100 — :trend_label

- Alert level    : :global/100
- Priority       : :priority

Interpretation to include:
- Activity ≥ 70  → "high activity — significant movement"
- Pressure ≥ 60  → "significant structural pressure"
- Concentration ≥ 60 → mention concentration on few entities
- Trend ↓ ≥ 40 → "continuous deterioration over multiple periods"
- Divergence ≥ 50 → "metrics moving in opposite directions — alert signal"',
    'severity_label.critical' => 'Critical 🔴',
    'severity_label.warning' => 'Warning 🟡',
    'severity_label.info' => 'Informational 🔵',
    'type_label.anomaly' => 'Anomaly detected',
    'type_label.trend' => 'Notable trend',
    'type_label.record' => 'Record detected',
    'type_label.info' => 'Periodic report',
];
