<?php

return [
    'title' => 'Blunx AI — Report',
    'badge.critical' => '🔴 Critical',
    'badge.warning' => '🟡 Warning',
    'badge.info' => '🔵 Informational',
    'type.anomaly' => 'Anomaly',
    'type.trend' => 'Trend',
    'type.record' => 'Record',
    'type.info' => 'Report',
    'dashboard' => 'Dashboard',
    'widget' => 'Widget',
    'generated_at' => 'Generated on',
    'attachment_title' => 'Detailed report attached',
    'attachment_desc' => 'The full report with analysis, reference data and recommendations is available in the PDF attached to this email.',
    'view_dashboard' => 'View dashboard',
    'footer_line1' => 'You are receiving this email because you enabled follow for this widget.',
    'footer_line2' => 'This report is automatically generated by Blunx AI.',
];
