<?php

return [
    'dashboard' => 'Dashboard',
    'widget' => 'Widget',
    'date' => 'Date',
    'footer' => 'Report automatically generated by Blunx AI. Internal use only.',
    'scores.title' => 'Blunx AI intelligence scores',
    'scores.signal' => 'Signal',
    'scores.score' => 'Score',
    'scores.interpretation' => 'Interpretation',
];
