<?php

namespace Blunx\AI\Console;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\DB;
use Blunx\AI\Support\BlunxDatabase;

/**
 * blunx:setup — lock the schema and create the Blunx AI tables.
 *
 * Requires storage/app/blunx_schema.json (generated by blunx:init).
 */
class SetupCommand extends Command
{
    protected $signature   = 'blunx:setup';
    protected $description = 'Lock the schema and create Blunx AI tables';

    public function handle(): void
    {
        $path = storage_path('app/blunx_schema.json');

        $this->line('');
        $this->line('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
        $this->line('🧠 <info>Blunx AI — Setup</info>');
        $this->line('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
        $this->line('');

        // ── Schema check ──────────────────────────────────────────
        if (!File::exists($path)) {
            $this->error("❌ Schema not found. Run first: php artisan blunx:init");
            return;
        }

        $data = json_decode(File::get($path), true);

        if (json_last_error() !== JSON_ERROR_NONE || empty($data)) {
            $this->error('❌ Schema file is corrupted or empty.');
            $this->line('   Fix storage/app/blunx_schema.json then re-run blunx:setup.');
            return;
        }

        $tableCount  = count($data);
        $columnCount = collect($data)->sum(fn($t) => count($t['columns'] ?? $t));

        $this->info("📋 Schema detected: <comment>{$tableCount} tables</comment>, <comment>{$columnCount} columns</comment>");
        $this->line('');

        // ── Lock ──────────────────────────────────────────────────
        // Unlock first: after a previous setup the file is read-only (0444),
        // otherwise writing fails (EPERM on Windows).
        @chmod($path, 0644);
        File::put($path, json_encode($data, JSON_UNESCAPED_UNICODE));
        chmod($path, 0444);

        $this->info('🔒 Schema optimized and locked.');

        // ── Create tables ─────────────────────────────────────────
        $this->line('');
        $this->info('🗄️  Creating Blunx AI tables...');

        $userTable = config('blunx.users.user_table', 'users');
        $userKey   = config('blunx.users.primary_key', 'id');

        $this->line("   User table: <info>{$userTable}</info> ({$userKey})");
        $this->line('');

        $this->createBlunxTables($userTable, $userKey);

        $this->line('');
        $this->info('✅ Blunx AI is installed and ready.');
        $this->line('');
        $this->line('   → <info>blunx:edit</info>  to update the schema at any time');
        $this->line('');
    }

    // ─────────────────────────────────────────────────────────────

    protected function createBlunxTables(string $userTable, string $userKey): void
    {
        $schema = Schema::connection(BlunxDatabase::mainConnection());

        if (!$schema->hasTable('blunx_conversations')) {
            $schema->create('blunx_conversations', function ($table) use ($userTable, $userKey) {
                $table->id();
                $table->uuid('uuid')->unique();
                $table->string('title')->nullable();
                $table->foreignId('user_id')->nullable()->constrained($userTable, $userKey)->onDelete('cascade');
                $table->timestamps();
            });
            $this->line("   ✅ blunx_conversations created");
        } else {
            $this->line("   ⏭️  blunx_conversations already exists");
        }

        if (!$schema->hasTable('blunx_messages')) {
            $schema->create('blunx_messages', function ($table) {
                $table->id();
                $table->uuid('uuid')->unique();
                $table->foreignId('conversation_id')->constrained('blunx_conversations')->onDelete('cascade');
                $table->enum('role', ['user', 'assistant']);
                $table->text('content');
                $table->text('intent')->nullable();
                $table->json('meta_data')->nullable();
                $table->timestamps();
            });
            $this->line("   ✅ blunx_messages created");
        } else {
            $this->line("   ⏭️  blunx_messages already exists");
        }

        if (!$schema->hasTable('blunx_feedbacks')) {
            $schema->create('blunx_feedbacks', function ($table) {
                $table->id();
                $table->foreignId('user_message_id')->constrained('blunx_messages')->onDelete('cascade');
                $table->foreignId('model_message_id')->constrained('blunx_messages')->onDelete('cascade');
                $table->text('comment')->nullable();
                $table->timestamp('resolved_at')->nullable();
                $table->timestamps();
            });
            $this->line("   ✅ blunx_feedbacks created");
        } else {
            $this->line("   ⏭️  blunx_feedbacks already exists");
        }

        if (!$schema->hasTable('blunx_dashboards')) {
            $schema->create('blunx_dashboards', function ($table) {
                $table->id();
                $table->uuid('uuid')->unique();
                $table->foreignId('user_id')->nullable()->constrained('users')->onDelete('cascade');
                $table->string('name');
                $table->string('description')->nullable();
                $table->timestamps();
            });
            $this->line("   ✅ blunx_dashboards created");
        } else {
            $this->line("   ⏭️  blunx_dashboards already exists");
        }

        if (!$schema->hasTable('blunx_dashboard_widgets')) {
            $schema->create('blunx_dashboard_widgets', function ($table) {
                $table->id();
                $table->foreignId('dashboard_id')->constrained('blunx_dashboards')->onDelete('cascade');
                $table->uuid('uuid')->unique();
                $table->string('title');
                $table->enum('type', ['chart', 'table']);
                $table->string('chart_type')->nullable();
                $table->text('sql_query');
                $table->string('ui_hint')->default('table');
                $table->string('label_column')->nullable();
                $table->json('data_columns')->nullable();
                $table->text('comment')->nullable();
                $table->json('reference_queries')->nullable();
                $table->timestamps();
            });
            $this->line("   ✅ blunx_dashboard_widgets created");
        } else {
            $this->line("   ⏭️  blunx_dashboard_widgets already exists");
        }

        if (!$schema->hasTable('blunx_insights')) {
            $schema->create('blunx_insights', function ($table) {
                $table->id();
                $table->uuid('uuid')->unique();
                $table->foreignId('user_id')->constrained()->cascadeOnDelete();
                $table->foreignId('dashboard_id')->constrained('blunx_dashboards')->cascadeOnDelete();
                $table->foreignId('widget_id')->constrained('blunx_dashboard_widgets')->cascadeOnDelete();
                $table->enum('type', ['anomaly', 'trend', 'record', 'info'])->default('info');
                $table->enum('severity', ['info', 'warning', 'critical'])->default('info');
                $table->text('message');
                $table->json('meta')->nullable();
                $table->boolean('is_read')->default(false);
                $table->timestamp('generated_at')->useCurrent();
                $table->longText('report_pdf')->nullable();
                $table->timestamps();
            });
            $this->line("   ✅ blunx_insights created");
        } else {
            $this->line("   ⏭️  blunx_insights already exists");
        }

        if (!$schema->hasTable('blunx_widget_insight_settings')) {
            $schema->create('blunx_widget_insight_settings', function ($table) {
                $table->id();
                $table->uuid('uuid')->unique();
                $table->foreignId('user_id')->constrained()->cascadeOnDelete();
                $table->foreignId('widget_id')->constrained('blunx_dashboard_widgets')->cascadeOnDelete();
                $table->enum('frequency', ['daily', 'weekly', 'monthly'])->default('daily');
                $table->boolean('notify_email')->default(false);
                $table->string('notify_threshold')->default('medium')->nullable();
                $table->json('metric_weights')->nullable();
                $table->string('email')->nullable();
                $table->timestamp('last_run_at')->nullable();
                $table->timestamp('next_run_at')->nullable();
                $table->uuid('job_uuid')->nullable();
                $table->timestamps();
                $table->unique(['user_id', 'widget_id']);
            });
            $this->line("   ✅ blunx_widget_insight_settings created");
        } else {
            $this->line("   ⏭️  blunx_widget_insight_settings already exists");
        }

        if (!$schema->hasTable('blunx_cache')) {
            $schema->create('blunx_cache', function ($table) {
                $table->string('key')->primary();
                $table->longText('value')->nullable();
                $table->integer('expiration')->nullable()->comment('Unix timestamp, null = permanent');
                $table->timestamps();
            });
            $this->line("   ✅ blunx_cache created");
        } else {
            $this->line("   ⏭️  blunx_cache already exists");
        }
    }
}